# Generated by Django 3.0.4 on 2020-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
